import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import LayoutView from "./layout.view";
// import type { Plan } from "@/types/plan";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Skeds Planner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body
        suppressHydrationWarning
        className={`${interSans.variable} antialiased dark`}
      >
        <LayoutView />
        <div>{children}</div>
      </body>
    </html>
  );
}
