import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutView from "./layout.view";
import type { Plan } from "@/types/plan";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Skeds Planner",
  description: "Generated by create next app",
};

const plans: Plan[] = [
  {
    id: 1,
    title: "Plano 12435",
    description: "Descrição do plano 1",
    data: [
      {
        id: 1,
        title: "Matemática",
        time: "16:30",
        subjects: [
          {
            title: "Geometria",
            topics: [
              {
                title: "Triângulos",
                done: false,
              },
              {
                title: "Circunferências",
                done: true,
              },
              {
                title: "Retas",
                done: false,
              },
            ],
          },
        ],
      },
      {
        id: 2,
        title: "Português",
        time: "17:30",
        subjects: [
          {
            title: "gramática",
            topics: [
              {
                title: "Triângulos",
                done: false,
              },
              {
                title: "Circunferências",
                done: true,
              },
              {
                title: "Retas",
                done: false,
              },
            ],
          },
          {
            title: "vocabulário",
            topics: [
              {
                title: "Triângulos",
                done: false,
              },
              {
                title: "Circunferências",
                done: true,
              },
              {
                title: "Retas",
                done: false,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Plano 2",
    description: "Descrição do plano 2",
    data: [
      {
        id: 1,
        title: "Matemática",
        time: "16:30",
        subjects: [
          {
            title: "Geometria",
            topics: [
              {
                title: "Triângulos",
                done: false,
              },
            ],
          },
        ],
      },
    ],
  },
];

export default function RootLayout() {
  return (
    <html lang="pt-BR">
      <body
        suppressHydrationWarning
        className={`${interSans.variable} antialiased dark`}
      >
        <LayoutView plans={plans}/>
        
      </body>
    </html>
  );
}
